import Legal, { H2 } from '../_components/Legal';

export const metadata = { title: 'Privacy Policy — Tide' };

export default function Privacy() {
  return (
    <Legal title="Privacy Policy" updated="September 2026">
      <p>
        Tide is an AI chat app with a mission to help clean the ocean. We keep the data we
        collect to the minimum needed to run the app. This policy explains what we collect,
        how your chats are handled, and who we work with.
      </p>

      <H2>No accounts</H2>
      <p>
        Tide doesn&apos;t ask for an email or password. When you start, we create an anonymous
        random identifier for your device. That&apos;s how we count messages and track impact
        without knowing who you are.
      </p>

      <H2>Your chats</H2>
      <p>
        <strong>We do not store your conversations on our servers.</strong> Your chat history
        lives only on your device. To generate a reply, the text of your current conversation
        is sent to our AI provider, which processes it to produce a response and does not use
        it to train their models. We keep only anonymous counts — how many messages have been
        sent — which power your impact dashboard.
      </p>

      <H2>What we collect</H2>
      <p>
        <strong>Message counts:</strong> the number of messages sent from your device and in
        total across the app. <strong>Device identifier:</strong> a random ID to count usage
        and enforce daily limits. <strong>Subscription status:</strong> whether you have an
        active premium subscription.
      </p>

      <H2>AI processing</H2>
      <p>
        Replies are generated by third-party AI providers (such as Groq and OpenAI). Only the
        text needed to answer your current message is sent to them, at the moment you send it.
      </p>

      <H2>Purchases</H2>
      <p>
        Premium subscriptions are handled by Apple and RevenueCat. We never see or store your
        card details. Premium revenue and our launch pool are used to fund verified ocean
        cleanup.
      </p>

      <H2>Who we share with</H2>
      <p>
        We rely on a few service providers to run Tide: Apple (payments), Cloudflare (hosting),
        RevenueCat (managing subscriptions), and AI providers (generating replies). They
        process data only to provide these services. We don&apos;t sell your data and we
        don&apos;t use third-party advertising trackers.
      </p>

      <H2>Children</H2>
      <p>
        Tide isn&apos;t directed to children under 13, and we don&apos;t knowingly collect
        their data.
      </p>

      <H2>Changes</H2>
      <p>If we update this policy we&apos;ll post the new version here with a fresh date.</p>
    </Legal>
  );
}
